In [ ]:
import pandas as pd

# Read csv file and header is at row 1 hence header = 0 ,if None is given header name are not picked
df = pd.read_csv('/content/sample_data/california_housing_test.csv',header =  0)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
df = pd.read_csv('/content/sample_data/california_housing_test.csv',names =  ['A','B'],header = 0)
df

                                                     A         B
-122.05 37.37 27.0 3885.0 661.0  1537.0 606.0   6.6085  344700.0
-118.30 34.26 43.0 1510.0 310.0  809.0  277.0   3.5990  176500.0
-117.81 33.78 27.0 3589.0 507.0  1484.0 495.0   5.7934  270500.0
-118.36 33.82 28.0 67.0   15.0   49.0   11.0    6.1359  330000.0
-119.67 36.33 19.0 1241.0 244.0  850.0  237.0   2.9375   81700.0
...                                                ...       ...
-119.86 34.42 23.0 1450.0 642.0  1258.0 607.0   1.1790  225000.0
-118.14 34.06 27.0 5257.0 1082.0 3496.0 1036.0  3.3906  237200.0
-119.70 36.30 10.0 956.0  201.0  693.0  220.0   2.2895   62000.0
-117.12 34.10 40.0 96.0   14.0   46.0   14.0    3.2708  162500.0
-119.63 34.42 42.0 1765.0 263.0  753.0  260.0   8.5608  500001.0

[3000 rows x 2 columns]

In [ ]:
# read only specific columns
df = pd.read_csv('/content/sample_data/california_housing_test.csv',usecols = ['longitude','latitude'])
df

      longitude  latitude
0       -122.05     37.37
1       -118.30     34.26
2       -117.81     33.78
3       -118.36     33.82
4       -119.67     36.33
...         ...       ...
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

[3000 rows x 2 columns]

In [ ]:
# make col as index
df = pd.read_csv('/content/sample_data/california_housing_test.csv',index_col =  ['longitude','latitude'])
df

,,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
longitude,latitude,,,,,,,
-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...
-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
# force data type
df = pd.read_csv('/content/sample_data/california_housing_test.csv',dtype = {'housing_median_age': 'int64'})
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [ ]:
# converter function demo
df = pd.read_csv(
    "data.csv",
    converters={"Salary": lambda x: int(x.replace("₹","").replace(",",""))}
)

print(df)

  Department Gender  Salary
0         IT      M   50000
1         IT      F   60000
2         HR      M   40000
3         HR      F   45000
4      Sales      M   70000
5      Sales      F   65000
------------------------------
             Salary
Department
HR          42500.0
IT          55000.0
Sales       67500.0
------------------------------
Gender            F        M
Department
HR          45000.0  40000.0
IT          60000.0  50000.0
Sales       65000.0  70000.0
------------------------------
Gender            F        M
Department
HR          45000.0  40000.0
IT          60000.0  50000.0
Sales       65000.0  70000.0
------------------------------

Gender                 F             M      All
Department
HR          45000.000000  40000.000000  42500.0
IT          60000.000000  50000.000000  55000.0
Sales       65000.000000  70000.000000  67500.0
All         56666.666667  53333.333333  55000.0

In [10]:
import pandas as pd

df1 = pd.DataFrame({
    "id": [1,2,3],
    "Name": ["A","B","C"]
})

df2 = pd.DataFrame({
    "id": [2,3,4],
    "Salary": [20000,30000,40000]
})

# inner join
df3 = pd.merge(df1,df2 ,on = 'id', how = 'inner')
df3

   id Name  Salary
0   2    B   20000
1   3    C   30000

In [7]:
# left join ,similar for right and outer
df4 = pd.merge(df1,df2 , on ='id',how ='left')
df4

   id Name   Salary
0   1    A      NaN
1   2    B  20000.0
2   3    C  30000.0

In [11]:
# join based on multiple col
df1 = pd.DataFrame({
    "id": [1,2,3],
    "Name": ["A","B","C"],
    "City": ["Mumbai","Pune","Delhi"]
})

df2 = pd.DataFrame({
    "id": [1,2,3],
    "Name": ["A","B","X"],
    "Salary": [20000,30000,40000]
})

pd.merge(df1, df2, on=["id","Name"], how="inner")

   id Name    City  Salary
0   1    A  Mumbai   20000
1   2    B    Pune   30000

In [12]:
# concat
df3 = pd.concat([df1, df2], axis=0)  # row-wise
df3

   id Name    City   Salary
0   1    A  Mumbai      NaN
1   2    B    Pune      NaN
2   3    C   Delhi      NaN
0   1    A     NaN  20000.0
1   2    B     NaN  30000.0
2   3    X     NaN  40000.0

In [13]:
df_c = pd.concat([df1, df2], axis=1)  # column-wise
df_c

   id Name    City  id Name  Salary
0   1    A  Mumbai   1    A   20000
1   2    B    Pune   2    B   30000
2   3    C   Delhi   3    X   40000

In [17]:
# join with tables having same column name
ds = df1.set_index("id").join(
   df2.set_index("id"),
   how="inner",
   lsuffix="_left",
   rsuffix="_right"
)

ds

   Name_left    City Name_right  Salary
id
1          A  Mumbai          A   20000
2          B    Pune          B   30000
3          C   Delhi          X   40000

In [3]:
import pandas as pd

dates = pd.date_range("2024-01-01", periods=4)
sales = pd.Series([100, 120, 150, 130], index=dates)

print(sales.diff(2))

2024-01-01     NaN
2024-01-02     NaN
2024-01-03    50.0
2024-01-04    10.0
Freq: D, dtype: float64

In [4]:
import pandas as pd

data = {
    "Sales": [100, 200, 150, 300, 250]
}

df = pd.DataFrame(data)

df["Rolling_Mean"] = df["Sales"].rolling(3).mean()

print(df)

   Sales  Rolling_Mean
0    100           NaN
1    200           NaN
2    150    150.000000
3    300    216.666667
4    250    233.333333

In [10]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]],dtype = 'float64',ndmin = 3,copy = True)
print(arr)

# properties
print(f'shape --{arr.shape}')
print(f'dim --{arr.ndim}')
print(f'type --{arr.dtype}')
print(f'size --{arr.size}')
arr = np.array(['I','Love','You'])
arr

[[[1. 2. 3.]
  [4. 5. 6.]]]
shape --(1, 2, 3)
dim --3
type --float64
size --6

array(['I', 'Love', 'You'], dtype='<U4')

In [14]:
arr_t = np.array([range(5),range(5)])
print(arr_t)

print(f'shape--{arr_t.shape}')
print(f't-shape---{arr_t.T.shape}')

[[0 1 2 3 4]
 [0 1 2 3 4]]
shape--(2, 5)
t-shape---(5, 2)

In [16]:
one = np.ones((2,3),dtype = int)
one

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
zero = np.zeros((3,2),dtype = int)
zero

empty = np.empty((2,2))
empty

array([[1.90928961e-315, 0.00000000e+000],
       [5.76469472e-317, 0.00000000e+000]])