In [ ]:
import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])
print(f'arr---{arr}')

# arr properties
print(f'ndim-- {arr.ndim}') #dimension
print(f'shape-- {arr.shape}') #shape
print(f'size-- {arr.size}') #no.of elements
print(f'datatype-- {arr.dtype}') #data type

arr---[[1 2 3 4]
 [5 6 7 8]]
ndim-- 2
shape-- (2, 4)
size-- 8
datatype-- int64

In [ ]:
# creating array

# we might not know what data the array will hold but we know its size or shape in that case we can use below to create array
# Zeros ,create array of zero
zeros = np.zeros((2,3),dtype='int16')
print(f'zeros array -- {zeros}')

print('-' * 30)

# ones ,create array of one
ones = np.ones((2,3),dtype='int16')
print(f'ones array -- {ones}')

print('-' * 30)

# empty ,create array filled with values based on state of memory
empty = np.empty((2,3))
print(f'empty array -- {empty}')

print('-' * 30)

# Create array with constant value
full = np.full((2,3),55,dtype = 'int')
print(f'full array -- {full}')

print('-' * 30)

# Create array with constant value columns is optional
eye = np.eye(3,5,k = 0,dtype = 'int')
print(f'eye array -- {eye}')

# identity
identity = np.identity(10)
print(f'identity array -- {identity}')

zeros array -- [[0 0 0]
 [0 0 0]]
------------------------------
ones array -- [[1 1 1]
 [1 1 1]]
------------------------------
empty array -- [[2.7e-322 2.7e-322 2.7e-322]
 [2.7e-322 2.7e-322 2.7e-322]]
------------------------------
full array -- [[55 55 55]
 [55 55 55]]
------------------------------
eye array -- [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
identity array -- [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]

In [ ]:
# arange(start,stop,step) only stop is mandatory and is not inclusive
arange = np.arange(1,10,1)
print(f'arange----{arange}')

print('-' * 30)

# linspace
lin,retstep = np.linspace(1,20,10,retstep = True,endpoint = False)
print(lin)
print(retstep)

# Transpose convert cols to rows and vice versa
arr_2d = np.array([range(5),range(5)])
print(f'2d---{arr_2d}')
print(f'2d transpose -- {arr_2d.T}')

arange----[1 2 3 4 5 6 7 8 9]
------------------------------
[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]
1.9
2d---[[0 1 2 3 4]
 [0 1 2 3 4]]
2d transpose -- [[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]]

In [ ]:
# random number generation
import numpy as np
rng = np.random.default_rng(9)

# random number
random = rng.random(8)
print(f'random --- {random}')
print('-' * 30)

# normal
normal  = rng.normal(100,10,20)
print(f'normal---{normal}')
print('-' * 30)
# choice
choice = rng.choice([1,2,3,4,5,6],4,replace = True,p=[0.1,0.1,0.2,0.2,0.3,0.1])
print(f'choice---{choice}')

# selects on random number
choice = rng.choice([1,2,3,4,5,6])
print(f'choice---{choice}')
print('-' * 30)

# shuffle re-arranges the elements of array in place
arr = np.arange(1,10,2)
print(f'before ---{arr}')
rng.shuffle(arr)
print(arr)
print('-' * 30)

# permutations returns new shuffled copy of the array
arr = np.arange(1,10,1)
print(rng.permutation(arr))
print(f'original -- {arr}')
print('-' * 30)

# uniform
uni = rng.uniform(10,20,5)
print(f'uni -- {uni}')
print('-' * 30)

# binomial eg -- tossed 10 coins ,repeated this for 5 times with probability of head as 50%
bi = rng.binomial(10,0.5,5)
print(f'bi---{bi}')
print('-' * 30)

# poisson, eg- in somehour you get 3 email some hour 0 or 1 but the average is 2 per hour
pois = rng.poisson(lam = 2,size  = 10)
print(pois)
print('-' * 30)

# exponential
expo = rng.exponential(scale = 1 ,size = 10 )
print(f'expo -- {expo}')

random --- [0.8702492  0.28681721 0.60314815 0.77753408 0.71607463 0.91538012
 0.86039365 0.91823763]
------------------------------
normal---[ 96.05647945  91.37595134  79.67447573 114.10423484  99.52367763
 125.22327411 108.26218249 102.77780527  93.42568941 113.92469204
  94.93710886 115.69949132  96.01638719 101.8595393   84.77329597
 123.43232382  99.05974171  96.14886411 108.10847634  91.08628164]
------------------------------
choice---[6 1 3 5]
choice---4
------------------------------
before ---[1 3 5 7 9]
[5 3 9 1 7]
------------------------------
[1 2 7 9 5 6 4 8 3]
original -- [1 2 3 4 5 6 7 8 9]
------------------------------
uni -- [13.77056371 16.23421641 17.82096131 10.78648894 19.31237453]
------------------------------
bi---[6 4 4 5 5]
------------------------------
[1 3 1 0 2 3 1 1 0 5]
------------------------------
expo -- [0.91330337 0.8022703  1.05378733 1.78352075 0.80671473 0.76301624
 0.74273851 0.54435082 0.98001084 1.67594101]

In [ ]:
# indexing and slicing
import numpy as np
arr = np.array([range(5),range(5,10)])
arr_1d = np.arange(start = 1 ,stop = 6)

print(f'1d-----{arr_1d}')
print(f'2d-----{arr}')

# get single element
print('-' * 30)
print(f'1d index--- {arr_1d[0]}')
print(f'1d multiple---{arr_1d[0:3:1]}')

# 2d
print('-' * 30)
print(f'2d index--- {arr[1,2]}')
print(f'2d multiple---{arr[0:2:1,1:3:1]}')

1d-----[1 2 3 4 5]
2d-----[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
1d index--- 1
1d multiple---[1 2 3]
------------------------------
2d index--- 7
2d multiple---[[1 2]
 [6 7]]

In [ ]:
# array operations  + ,- , / , %,**,*
a = np.array([1,2,3,4])
b = np.array([5,4,2,3])

# +
print(f'+---{a + b}')
print('-' * 30)

# -
print(f'----{a - b}')
print('-' * 30)

a_2d = np.array([[1,2,3,4],[5,6,7,8]])
b_2d = np.array([[5,4,6,2],[1,2,4,5]])
# +
print(f'+---{a_2d + b_2d}')
print('-' * 30)

+---[6 6 5 7]
------------------------------
----[-4 -2  1  1]
------------------------------
+---[[ 6  6  9  6]
 [ 6  8 11 13]]
------------------------------

In [ ]:
# Aggregation

arr = np.array([1,2,3,4,6])

print(f'sum -- {arr.sum()}')
print('-' * 30)

print(f'max -- {arr.max()}')
print('-' * 30)

print(f'min -- {arr.min()}')
print('-' * 30)

print(f'std -- {arr.std()}')
print('-' * 30)

print(f'mean -- {arr.mean()}')
print('-' * 30)

# axis = 0(row) and axis = 1(column)
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(f'max -- {arr_2d.max(axis = 1)}')
print('-' * 30)

# matrix operation
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a @ b)
print('-' * 30)

# Transpose
print(f'Before --- {a}')
print(f'Transpose --- {a.T}')

sum -- 16
------------------------------
max -- 6
------------------------------
min -- 1
------------------------------
std -- 1.7204650534085253
------------------------------
mean -- 3.2
------------------------------
max -- [4 8]
------------------------------
[[19 22]
 [43 50]]
------------------------------
Before --- [[1 2]
 [3 4]]
Transpose --- [[1 3]
 [2 4]]

In [ ]:
# Boolean operations
arr = np.array([[1,2,3],[4,5,6]])
print(arr > 3)

# round
arr_f = np.array([1.2222,3.4444,6.4444])
print(arr_f.round(2))

# reshape
arr_r = np.array([1,2,3,4,5,6])
print(arr_r.reshape(2,-1))

[[False False False]
 [ True  True  True]]
[1.22 3.44 6.44]
[[1 2 3]
 [4 5 6]]

In [ ]:
# join based on multiple col
df1 = pd.DataFrame({
    "id": [1,2,3],
    "Name": ["A","B","C"],
    "City": ["Mumbai","Pune","Delhi"]
})

df2 = pd.DataFrame({
    "id": [1,2,3],
    "Name": ["A","B","X"],
    "Salary": [20000,30000,40000]
})

pd.merge(df1, df2, on=["id","Name"], how="inner")

   id Name    City  Salary
0   1    A  Mumbai   20000
1   2    B    Pune   30000

In [ ]:
# concat
df3 = pd.concat([df1, df2], axis=0)  # row-wise
df3

   id Name    City   Salary
0   1    A  Mumbai      NaN
1   2    B    Pune      NaN
2   3    C   Delhi      NaN
0   1    A     NaN  20000.0
1   2    B     NaN  30000.0
2   3    X     NaN  40000.0

In [ ]:
df_c = pd.concat([df1, df2], axis=1)  # column-wise
df_c

   id Name    City  id Name  Salary
0   1    A  Mumbai   1    A   20000
1   2    B    Pune   2    B   30000
2   3    C   Delhi   3    X   40000

In [ ]:
# join with tables having same column name
ds = df1.set_index("id").join(
   df2.set_index("id"),
   how="inner",
   lsuffix="_left",
   rsuffix="_right"
)

ds

   Name_left    City Name_right  Salary
id
1          A  Mumbai          A   20000
2          B    Pune          B   30000
3          C   Delhi          X   40000

In [ ]:
import pandas as pd

dates = pd.date_range("2024-01-01", periods=4)
sales = pd.Series([100, 120, 150, 130], index=dates)

print(sales.diff(2))

2024-01-01     NaN
2024-01-02     NaN
2024-01-03    50.0
2024-01-04    10.0
Freq: D, dtype: float64

In [ ]:
import pandas as pd

data = {
    "Sales": [100, 200, 150, 300, 250]
}

df = pd.DataFrame(data)

df["Rolling_Mean"] = df["Sales"].rolling(3).mean()

print(df)

   Sales  Rolling_Mean
0    100           NaN
1    200           NaN
2    150    150.000000
3    300    216.666667
4    250    233.333333

In [ ]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]],dtype = 'float64',ndmin = 3,copy = True)
print(arr)

# properties
print(f'shape --{arr.shape}')
print(f'dim --{arr.ndim}')
print(f'type --{arr.dtype}')
print(f'size --{arr.size}')
arr = np.array(['I','Love','You'])
arr

[[[1. 2. 3.]
  [4. 5. 6.]]]
shape --(1, 2, 3)
dim --3
type --float64
size --6

array(['I', 'Love', 'You'], dtype='<U4')

In [ ]:
arr_t = np.array([range(5),range(5)])
print(arr_t)

print(f'shape--{arr_t.shape}')
print(f't-shape---{arr_t.T.shape}')

[[0 1 2 3 4]
 [0 1 2 3 4]]
shape--(2, 5)
t-shape---(5, 2)

In [ ]:
one = np.ones((2,3),dtype = int)
one

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

print(arr.sum(axis= 0))
print(arr.sum(axis= 1))

print('*' * 40)

print(arr.prod())

print('*' * 40)

print(arr.mean())
print(arr.std())
print(arr.var())

print('*' * 40)

print(arr.cumsum())
print(arr.cumprod())
print('*' * 40)

print((arr> 2).any(axis = 0))
print((arr > 0).all())
print('*' * 40)

print(np.median(arr,axis = 0))
print(np.percentile(arr,75,axis =0))

arr_d = [1,2,3,4,2,3,1]
print(np.unique(arr_d))
print(np.unique(arr_d,return_counts= True,return_inverse=True))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 7  9 11 13 15]
[15 40]
****************************************
3628800
****************************************
5.5
2.8722813232690143
8.25
****************************************
[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]
****************************************
[ True  True  True  True  True]
True
****************************************
[3.5 4.5 5.5 6.5 7.5]
[4.75 5.75 6.75 7.75 8.75]
[1 2 3 4]
(array([1, 2, 3, 4]), array([0, 1, 2, 3, 1, 2, 0]), array([2, 2, 2, 1]))

In [ ]:
# ELEMENTWISE operations
import numpy as np

arr = [1,2,3,4,5,-6]
print(np.abs(arr))
print(np.exp(arr))
print(np.log([1,10,20]))
np.round([1.2323,1.3232],2)

[1 2 3 4 5 6]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 2.47875218e-03]
[0.         2.30258509 2.99573227]

array([1.23, 1.32])

In [ ]:
arr = [[1,5],[4,7]]
inv = np.linalg.inv(arr)
print(inv)

print(arr @ inv)

[[-0.53846154  0.38461538]
 [ 0.30769231 -0.07692308]]
[[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]

In [ ]:
# sorting arrays
arr = np.array([1,92,38,76,25,19])
copy = np.sort(arr)[::-1]
print(copy)

arr_2d = [[89,29,39,20],[35,45,23,55]]
sor = np.sort(arr_2d,axis = 0)
print(sor)

print(arr.argsort())

[92 76 38 25 19  1]
[[35 29 23 20]
 [89 45 39 55]]
[0 5 4 2 3 1]

In [ ]:
# stacking array

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.hstack((a,b))
print(c)

d = np.vstack((a,b))
print(d)

e = np.concatenate([a,b],axis = 0)
print(e)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

In [ ]:
# split
af = np.array([1,2,3,4,5,6])
s = np.split(af,3)
print(s)

d = np.array_split(af,4)
print(d)

arr_2d = np.array([[1,2,34,5],[6,98,23,23]])
print(arr_2d)
e = np.hsplit(arr_2d,2)
print(e)


arr_2d = np.array([[1,2],[34,5],[6,98],[23,23]])
print(arr_2d)
e = np.vsplit(arr_2d,2)
print(e)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[[ 1  2 34  5]
 [ 6 98 23 23]]
[array([[ 1,  2],
       [ 6, 98]]), array([[34,  5],
       [23, 23]])]
[[ 1  2]
 [34  5]
 [ 6 98]
 [23 23]]
[array([[ 1,  2],
       [34,  5]]), array([[ 6, 98],
       [23, 23]])]

In [ ]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])
val = np.repeat(arr,2,axis= 1)
print(val)

arr_1 = np.tile(arr,3)
arr_1

[[1 1 2 2 3 3]
 [4 4 5 5 6 6]]

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [5]:
import numpy as np
arr = np.array([[1,2],[3,4]])


app = np.append(arr,np.array([[7,8],[9,0]]),axis= 1)
print(app)

ins = np.insert(arr,1,[11,12],axis= None)
print(ins)

dels = np.delete(arr,1,axis =0)
dels

[[1 2 7 8]
 [3 4 9 0]]
[ 1 11 12  2  3  4]

array([[1, 2]])

In [6]:
def f(x,y):
  return 10 * x + y

b = np.fromfunction(f, (5,4),dtype = int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [16]:
# view v/s copy

import numpy as np
# slicing gives view and any change to view causes change in original array
arr = np.array([1,2,3,4,5,6,7,8])
data = arr[1:5:]
print(data)

data[0] = 10
print(arr)

arr_1 = np.array([1,2,3,4,5,6,7,8,9])
dat_1 = arr_1[1:5:].copy()
print(dat_1)
dat_1[0] = 10
print(arr_1)
print(dat_1)

[2 3 4 5]
[ 1 10  3  4  5  6  7  8]
[2 3 4 5]
[1 2 3 4 5 6 7 8 9]
[10  3  4  5]

In [28]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)

a = arr.reshape(5,2)
print(a)

b = arr.ravel()
print(b)

[[1 2 3 4 5]
 [6 7 8 9 0]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]
[1 2 3 4 5 6 7 8 9 0]

In [27]:

arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr)

arr.resize((3,2))
print(arr)

[[1 2 3 4 5]
 [6 7 8 9 0]]
[[1 2]
 [3 4]
 [5 6]]

In [35]:
import numpy as np

arr = np.array([1,2,3,4])
print(np.expand_dims(arr,axis = 0))

print(np.expand_dims(arr,axis = 1))


arr = np.array([[1,2,3,4],[5,6,7,8]])
print(np.expand_dims(arr,axis = 0))

print(np.expand_dims(arr,axis = 1))

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]
[[[1 2 3 4]
  [5 6 7 8]]]
[[[1 2 3 4]]

 [[5 6 7 8]]]

In [40]:
import numpy as np

arr = np.array([[[1,2,3,4],[5,6,7,8]]])
print(arr.shape)
print(np.squeeze(arr))

(1, 2, 4)
[[1 2 3 4]
 [5 6 7 8]]

In [46]:
# fancy indexing ,select element based on index arr list
arr = np.array([10,20,30,40,50,60,70])
print(arr[[0,4,3,6]])


arr_2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr_2)

print(arr_2[[0,1,2], [2,1,0]])

[10 50 40 70]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 5 7]

In [55]:
# to check view or copy

arr = np.array([1,2,3,4,8,9])
arr_1 = arr[::]
arr_2 = arr.reshape(3,2)
arr_3 = arr.view()
print(arr_1.base is arr) #True means it is view
print(arr_2.base is arr) #True means it is view
print(arr_3.base is arr) #True means it is view

True
True
True

In [59]:
# type conversion

arr = np.array([1.2,3.4,5.6,7.8])
print(arr.dtype)

arr_1 = arr.astype('int')
print(arr_1.dtype)
print(arr_1)

float64
int64
[1 3 5 7]